---
version: "3"

services:
  queue:
    image: redis:7-alpine
    container_name: redis_multicode
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass foobared
    volumes:
      - ./redis/local_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  data-volume:
